### ISSUE TITLE
[OpenELEC] By default, torrent payloads downloaded to RAM and fill it all quickly

### ISSUE THREAD

**Issue by bam80** [DiMartinoXBMC/plugin.video.torrenter#2]
It is not acceptable to use /tmp as torrents storage in OpenELEC due it's tmpfs there

**Comment by DiMartinoXBMC** [comment]
added check if storage is set on every update, telling user to set it

**Comment by bam80** [comment]
Maybe just change default path instead? I bet no one has tmpfs folders in $HOME ..
