### ISSUE TITLE
add to library local torrents

### ISSUE THREAD

**Issue by sonics007** [DiMartinoXBMC/plugin.video.torrenter#28]
is it possible to add to context menu option add to library. im using torrenter to play downloaded .torrents files from privates tracker and would be great to add these files to my library

**Comment by DiMartinoXBMC** [comment]
From what I understand you want to have in your library (with posters and other metadata) a one click to play video.
This is what .strm files and playSTRM function are for.

Just create in you Video Library folder a text file named "Movie name (YEAR).strm" with content "plugin://plugin.video.torrenter/?action=playSTRM&url=D%3A%5Ctorrents%5CTorrenter%5Ctor.torrent" where "D%3A%5Ctorrents%5CTorrenter%5Ctor.torrent" is actually url-encoded (google it) path to torrent D:\torrents\Torrenter\tor.torrent

**Comment by sonics007** [comment]
thank you.its working. but would be great to have it in context menu. btw when i added movie to my library it doesnt show flag like sd, hd, 3d. could u help me with that?

**Comment by DiMartinoXBMC** [comment]
No, I don't know how to da that.

**Comment by lidormalicb** [comment]
hi , im trying to play a video from my library using this "plugin://plugin.video.torrenter/?action=playSTRM&url=C%3A%5CUsers%5Cyoel%5CAppData%5CRoaming%5CKodi%5Cuserdata%5Caddon_data\Moviesmb=location:C%3A%5CUsers%5Cusername%5CAppData%5CRoaming%5CKodi%5Cuserdata%5Caddon_data\Movies"
 
but i get error .

**Comment by lidormalicb** [comment]
the torrent loads but dosent play. thanks .

**Comment by DiMartinoXBMC** [comment]
it works only direct with torrent files, so you would have to have some script that automaticlly creat such strm files, like [Pulsar Extensions, Automatic Library Integration, list from Trakt, IMDB](https://forums.tvaddons.ag/addon-releases/35403-pulsar-extensions-automatic-library-integration-list-trakt-imdb.html)

**Comment by lidormalicb** [comment]
It was also tried with torrent files (file srtm received the full name of the torrent). Torrent file was not downloaded the file at all, it was a link is only lowered without watching.
