### ISSUE TITLE
После обновления KODi начались спецэффекты

### ISSUE THREAD

**Issue by inpos** [DiMartinoXBMC/plugin.video.torrenter#32]
Привет. Вчера в OSMC прилитело обновление KODI на 16 версию.
Железка - RPi2.
Наблюдается следующее:

1. Неработающее избранное. Добавляем торрент в избранное. Всё работает. Открывается из избранного, показывает. Перезагрузили KODI (или целиком машинку) - в избранном торрент есть, но, при открытии от туда, внутри ни одного файла. При входе через поиск в этот же торрент - всё отлично. Удаляем из избранного, добавляем снова. Работает до перезапуска.

2. Не удаляется торрент после аварийного останова воспроизведения. Хранение торрентов настроено в режиме "Удалять файлы". До обновления, если аварийно завершался просмотр, открываешь торрент, появляется окно "Проверка файлов" (ни разу не дождался завершения). Жмёшь "Отмена" и внизу появляется чудесное сообщения о том, что хранилище отчищено (кстати, после обновления эта надпись не появляется вообще). Теперь сколько раз бы ты ни открыл этот файл, каждый раз пытается проверить файлы.

3. Через раз зависает. Тут может быть проблема с script.module.torrent2http. Туда я тоже отписал, т.к. там проблема со сжираением оперативки начисто (примерно через 20 минут просмотра) процессом torrent2http. Хотя, когда именно эта ситуация происходит, то просто аварийно завершается просмотр.

Как говорится, "не было печали, обновлений накачали".
Полтора месяца назад настроил себе это всё хозяйство.
До вчерашнего вечера смотрел фильмы 1080p и нарадоваться не мог.

**Comment by DiMartinoXBMC** [comment]
Нужны логи, как их делать читай внизу http://xbmc.ru/forum/showpost.php?p=71834&postcount=1
