### ISSUE TITLE
Add mipsel For vu+ receivers? 

### ISSUE THREAD

**Issue by Albertron86** [DiMartinoXBMC/plugin.video.torrenter#33]
Hi, is possible to add mipsel devices? 
In Vu+ receivers is possible install kodi but the diferent torrenter version not work. Best regards

**Comment by CyberSoftx** [comment]
Hi i join to request too.

Many thanks in advance!

**Comment by DiMartinoXBMC** [comment]
Well I'll ask my C++ bodies if they can cross-compile python-libtorrent, meanwhile could you try just install it in the system? like by apt-get

**Comment by Albertron86** [comment]
Thanks you very much to try compile.I do not understand how to install by apt-get.As the plugin is installed that way?

**Comment by DiMartinoXBMC** [comment]
what you need for plugin to work is python-libtorrent in your system (not default P2P-player in Settings, so switch to it)

**Comment by CyberSoftx** [comment]
Hi many thanks for you help, python-libtorrent not work as well on our box, what we need for do you plugin work on our box?

Regards!!!

**Comment by inpos** [comment]
we have built libtorrent python-module for mipsel.
Please wait while we create test plugin for you.
By the way, what OS you use on Vu+ ? OpenELEC, OSMC or other?

**Comment by Albertron86** [comment]
The OS is enigma2.

**Comment by DiMartinoXBMC** [comment]
inpos compiled python-libtorrent for you, I added it in MyShows.ru Kodi Repo.
Please update python-libtorrent Program plugin up to "1.0.9f", click on python-libtorrent to test it.
Then send us log here.

**Comment by Albertron86** [comment]
Hi. I have update the plugin to 1.0.9f versión, but when i open  torrent file with torrenter, its said script error. This is my xbmc log file:

############## XBMC CRASH LOG ###############

################ SYSTEM INFO ################
 Date: Fri Mar 11 19:33:47 CET 2016
 XBMC Options: 
 Arch: mips
 Kernel: Linux 3.13.5 #1 SMP Fri Jan 15 20:35:44 CET 2016
 Release: lsb_release not available
############## END SYSTEM INFO ##############

############### STACK TRACE #################
gdb not installed, can't get stack trace.
############# END STACK TRACE ###############

################# LOG FILE ##################

﻿19:32:47 T:1981923328  NOTICE: special://profile/ is mapped to: special://masterprofile/
19:32:47 T:1981923328  NOTICE: -----------------------------------------------------------------------
19:32:47 T:1981923328  NOTICE: Starting XBMC (13.2 Git:20150206-ed2750e). Platform: MIPS Linux 32-bit
19:32:47 T:1981923328  NOTICE: Using Debug XBMC x32 build, compiled Jan 15 2016 by GCC 4.9.1 for MIPS Linux 32-bit 3.13.0
19:32:47 T:1981923328 WARNING: Unable to determine Linux distribution
19:32:47 T:1981923328  NOTICE: Running on Linux 32-bit (Unknown, 3.13.5 mips)
19:32:47 T:1981923328  NOTICE: Host CPU: BCM7346B2 STB platform, 2 cores available
19:32:47 T:1981923328  NOTICE: special://xbmc/ is mapped to: /usr/share/xbmc
19:32:47 T:1981923328  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/xbmc
19:32:47 T:1981923328  NOTICE: special://masterprofile/ is mapped to: /media/hdd/.xbmc/userdata
19:32:47 T:1981923328  NOTICE: special://home/ is mapped to: /media/hdd/.xbmc
19:32:47 T:1981923328  NOTICE: special://temp/ is mapped to: /media/hdd/.xbmc/temp
19:32:47 T:1981923328  NOTICE: The executable running is: /usr/lib/xbmc/xbmc.bin
19:32:47 T:1981923328  NOTICE: Local hostname: vusolo2
19:32:47 T:1981923328  NOTICE: Log File is located: /media/hdd/.xbmc/temp/xbmc.log
19:32:47 T:1981923328 WARNING: Unicode properties are not enabled in PCRE lib, support for national symbols may be limited!
19:32:47 T:1981923328  NOTICE: Consider installing PCRE lib version 8.10 or later with enabled Unicode properties and UTF-8 support. Your PCRE lib version: 8.35 2014-04-04
19:32:47 T:1981923328  NOTICE: -----------------------------------------------------------------------
19:32:47 T:1981923328   DEBUG: ConsoleKit.Manager: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.ConsoleKit was not provided by any .service files
19:32:47 T:1981923328   DEBUG: UPower: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
19:32:47 T:1981923328   DEBUG: ConsoleKit.Manager: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.ConsoleKit was not provided by any .service files
19:32:47 T:1981923328   DEBUG: DeviceKit.Power: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.DeviceKit.Disks was not provided by any .service files
19:32:47 T:1981923328   DEBUG: UPower: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
19:32:47 T:1981923328  NOTICE: load settings...
19:32:47 T:1981923328   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
19:32:47 T:1981923328   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/linux.xml
19:32:47 T:1981923328  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
19:32:47 T:1981923328  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
19:32:47 T:1981923328  NOTICE: Default DVD Player: dvdplayer
19:32:47 T:1981923328  NOTICE: Default Video Player: dvdplayer
19:32:47 T:1981923328  NOTICE: Default Audio Player: paplayer
19:32:47 T:1981923328  NOTICE: Disabled debug logging due to GUI setting. Level 0.
19:32:47 T:1981923328  NOTICE: Log level changed to 0
19:32:47 T:1981923328  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
19:32:47 T:1981923328   DEBUG: CPlayerCoreConfig::<ctor>: created player DVDPlayer for core 1
19:32:47 T:1981923328   DEBUG: CPlayerCoreConfig::<ctor>: created player oldmplayercore for core 1
19:32:47 T:1981923328   DEBUG: CPlayerCoreConfig::<ctor>: created player PAPlayer for core 3
19:32:47 T:1981923328   DEBUG: CPlayerCoreConfig::<ctor>: created player E2Player for core 4
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: system rules
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: rtv
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: hdhomerun/myth/mms/udp
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: lastfm/shout
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: rtmp
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: rtsp
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: streams
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: aacp/sdp
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: mp2
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: dvd
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: dvdimage
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: sdp/asf
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: nsv
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: radio
19:32:47 T:1981923328   DEBUG: CPlayerSelectionRule::Initialize: creating rule: dgb
19:32:47 T:1981923328  NOTICE: Loaded playercorefactory configuration
19:32:47 T:1981923328  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
19:32:47 T:1981923328  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
18:32:47 T:1981923328    INFO: creating subdirectories
18:32:47 T:1981923328    INFO: userdata folder: special://masterprofile/
18:32:47 T:1981923328    INFO: recording folder:
18:32:47 T:1981923328    INFO: screenshots folder:
18:32:47 T:1981923328    INFO: load language info file: special://xbmc/language/Spanish/langinfo.xml
18:32:47 T:1981923328   DEBUG: trying to set locale to es_ES.UTF-8
18:32:47 T:1981923328    INFO: global locale set to C
18:32:47 T:1981923328    INFO: load Spanish language file, from path: special://xbmc/language/
18:32:48 T:1981923328   DEBUG: POParser: loaded 3162 strings from file /usr/share/xbmc/language/Spanish/strings.po
18:32:48 T:1981923328   DEBUG: POParser: loaded 0 strings from file /usr/share/xbmc/language/English/strings.po
18:32:48 T:1981923328  NOTICE: Running database version Addons16
18:32:48 T:1981923328   DEBUG: SECTION:LoadDLL(special://xbmcbin/system/libcpluff-mips.so)
18:32:48 T:1981923328   DEBUG: Loading: /usr/lib/xbmc/system/libcpluff-mips.so
18:32:48 T:1981923328    INFO: ADDON: cpluff: 'Could not read plug-in directory /usr/lib/xbmc/addons: No such file or directory'
18:32:48 T:1981923328  NOTICE: ADDONS: Using repository repository.xbmc.org
18:32:48 T:1981923328  NOTICE: ADDONS: Using repository repository.myshows.me
18:32:48 T:1981923328   DEBUG: LoadMappings - loaded node "Motorola Nyxboard Hybrid"
18:32:48 T:1981923328   DEBUG: LoadMappings - loaded node "CEC Adapter"
18:32:48 T:1981923328   DEBUG: LoadMappings - loaded node "Pulse-Eight CEC Adapter"
18:32:48 T:1981923328   DEBUG: LoadMappings - loaded node "iMON HID device"
18:32:48 T:1981923328   DEBUG: CPeripheralBusUSB - initialised udev monitor
18:32:48 T:1981445264  NOTICE: Thread PeripBusUSBUdev start, auto delete: false
18:32:48 T:1981923328   DEBUG: UDisks: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UDisks was not provided by any .service files
18:32:48 T:1981923328   DEBUG: DeviceKit.Disks: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.DeviceKit.Disks was not provided by any .service files
18:32:48 T:1981923328   DEBUG: Selected UDev as storage provider
18:32:48 T:1981923328  NOTICE: InitWindowSystem: Using EGL Implementation: dvbbox
18:32:48 T:1981923328   DEBUG: EGL initial desktop resolution  @ 50.00 - Full Screen
18:32:48 T:1981923328   DEBUG: EGL initial desktop resolution 1280x720 @ 50.00 - Full Screen 3DSBS
18:32:48 T:1981923328   DEBUG: EGL initial desktop resolution 1280x720 @ 50.00 - Full Screen 3DTB
18:32:48 T:1981923328  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 50.000000 Hz
18:32:48 T:1981923328  NOTICE: Previous line repeats 2 times.
18:32:48 T:1981923328  NOTICE: Found (1280x720@50.000000) at 16, setting to RES_DESKTOP at 16
18:32:48 T:1981923328  NOTICE: Checking resolution 16
18:32:48 T:1981923328   DEBUG: CreateWindow: Created surface of size 1280x720
18:32:48 T:1981923328  NOTICE: GL_VENDOR = Broadcom
18:32:48 T:1981923328  NOTICE: GL_RENDERER = VideoCore IV HW (V3D-410)
18:32:48 T:1981923328  NOTICE: GL_VERSION = OpenGL ES 2.0
18:32:48 T:1981923328  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
18:32:48 T:1981923328   DEBUG: GLES: Extension Support Test - GL_NVX_gpu_memory_info NO
18:32:48 T:1981923328  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_APPLE_rgb_422 GL_OES_packed_depth_stencil GL_EXT_debug_marker GL_EXT_multisampled_render_to_texture GL_EXT_texture_format_BGRA8888
18:32:48 T:1981923328   DEBUG: GLES: Extension Support Test - GL_EXT_texture_format_BGRA8888 YES
18:32:48 T:1981923328   DEBUG: GLES: Extension Support Test - GL_IMG_texture_format_BGRA8888 NO
18:32:48 T:1981923328   DEBUG: GLES: Extension Support Test - GL_APPLE_texture_format_BGRA8888 NO
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GL: Pixel Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Fragment Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GUI Shader [guishader_frag_default.glsl]- Initialise successful : 0x13d9808
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GL: Pixel Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Fragment Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GUI Shader [guishader_frag_texture.glsl]- Initialise successful : 0x13dbaf0
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GL: Pixel Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Fragment Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GUI Shader [guishader_frag_multi.glsl]- Initialise successful : 0x13de5d0
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GL: Pixel Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Fragment Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GUI Shader [guishader_frag_fonts.glsl]- Initialise successful : 0x13e1120
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GL: Pixel Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Fragment Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GUI Shader [guishader_frag_texture_noblend.glsl]- Initialise successful : 0x13e3c58
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GL: Pixel Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Fragment Shader compiled successfully
18:32:48 T:1981923328   DEBUG: GUI Shader [guishader_frag_multi_blendcolor.glsl]- Initialise successful : 0x13e6640
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compilation log:
18:32:48 T:1981923328   DEBUG: GL: Vertex Shader compiled successfully
18:32:48

**Comment by DiMartinoXBMC** [comment]
Log not full, upload on pastebin or xbmclogs.com

**Comment by Albertron86** [comment]
Sorry, the file log is too long and i cant post here. I upload here: https://mega.nz/#!8g1CTA5Y!yTD0jx3GpCvoEpBXnZ0EyKjvEU8HNg2ReVoGWgOF4ew

**Comment by Albertron86** [comment]
Pastebin : http://pastebin.com/ZEwmxNeA

**Comment by DiMartinoXBMC** [comment]
ok, log helped, inpos build now two versions! update to 1.0.9g and try again. Also don't forget to switch to pyrrent2http player by inpos in Torrenter settings.

**Comment by Albertron86** [comment]
Hi, kodi dont update to 1.0.9g automatically, where can I download this versión?

**Comment by DiMartinoXBMC** [comment]
[here](https://bitbucket.org/DiMartino/myshows.me-kodi-repo/raw/c0f7c5c96016bf5501cded18bbfcd884ccef74a3/repo/script.module.libtorrent/script.module.libtorrent-1.0.9g.zip) or you can create a new profile in Kodi, update and login back to yours

**Comment by Albertron86** [comment]
Hi. Now if that works perfectly . Thank you very much , have done a fantastic job , thank you very much again.

**Comment by CyberSoftx** [comment]
Albertron86 now we can see torrents files on our boxes?

**Comment by Albertron86** [comment]
Yes, i have seen a torrent file now and works perfectly with the last versión 1.0.9g.

**Comment by Albertron86** [comment]
I have a vu+ solo2 with xbmc versión gotham

**Comment by CyberSoftx** [comment]
Many many thanks for you big and great work!!!!

Regards!!!
