### ISSUE TITLE
cant play any file from any torrrenter searcher

### ISSUE THREAD

**Issue by fogenous** [DiMartinoXBMC/plugin.video.torrenter#58]
Hi!

I have installed latest version of torrenter from your repo but once i try to search anything, it finds all torrents from all sites i have installed and once i double click to play, it doesnt start playing or show anything. It just shows working for one sec and that's it. In kodi.log file i get this:

`:58 4071.531250 T:1309668336  NOTICE: ### [Torrenter v.2.5.2m]: Torrenter v.2.5.2m
00:00:58 4071.589355 T:1309668336  NOTICE: ### [Torrenter v.2.5.2m]: SYS ARGV: ['plugin://plugin.video.torrenter/', '16', '?action=context&url=RuTrackerOrg%3a%3ahttp%3a%2f%2fdl.rutracker.net%2fforum%2fdl.php%3ft%3d5265351']
00:00:58 4071.712402 T:1309668336  NOTICE: ### [Torrenter v.2.5.2m]: Garbage collector: collected 3145 objects.
00:00:58 4071.850830 T:1956832176   ERROR: GetDirectory - Error getting plugin://plugin.video.torrenter/?action=context&url=RuTrackerOrg%3a%3ahttp%3a%2f%2fdl.rutracker.net%2fforum%2fdl.php%3ft%3d5265351
00:00:58 4071.851807 T:1956832176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.torrenter/?action=context&url=RuTrackerOrg%3a%3ahttp%3a%2f%2fdl.rutracker.net%2fforum%2fdl.php%3ft%3d5265351) failed
00:01:04 4077.768311 T:1309668336  NOTICE: ### [Torrenter v.2.5.2m]: Torrenter v.2.5.2m
00:01:04 4077.823242 T:1309668336  NOTICE: ### [Torrenter v.2.5.2m]: SYS ARGV: ['plugin://plugin.video.torrenter/', '17', '?action=context&url=RuTrackerOrg%3a%3ahttp%3a%2f%2fdl.rutracker.net%2fforum%2fdl.php%3ft%3d5265351']
00:01:04 4077.934082 T:1309668336  NOTICE: ### [Torrenter v.2.5.2m]: Garbage collector: collected 1436 objects.
00:01:04 4078.079590 T:1956832176   ERROR: GetDirectory - Error getting plugin://plugin.video.torrenter/?action=context&url=RuTrackerOrg%3a%3ahttp%3a%2f%2fdl.rutracker.net%2fforum%2fdl.php%3ft%3d5265351
00:01:04 4078.080811 T:1956832176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.torrenter/?action=context&url=RuTrackerOrg%3a%3ahttp%3a%2f%2fdl.rutracker.net%2fforum%2fdl.php%3ft%3d5265351) failed
00:02:47 4180.421387 T:1539740656  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG file path is not configured. EPG not loaded.
00:03:33 4226.953613 T:1562371056  NOTICE: ### [Torrenter v.2.5.2m]: Torrenter v.2.5.2m
00:03:33 4227.010254 T:1562371056  NOTICE: ### [Torrenter v.2.5.2m]: SYS ARGV: ['plugin://plugin.video.torrenter/', '18', '?action=context&url=ThePirateBay%3a%3amagnet%3a%3fxt%3durn%3abtih%3af949ea68b119a238fd7d4accb93bbea5ceb62016%26dn%3dMr.Robot.S02E08.1080p.HDTV.x264-BRISK%255BPRiME%255D%26tr%3dudp%253A%2f%2ftracker.leechers-paradise.org%253A6969%26tr%3dudp%253A%2f%2fzer0day.ch%253A1337%26tr%3dudp%253A%2f%2fopen.demonii.com%253A1337%26tr%3dudp%253A%2f%2ftracker.coppersurfer.tk%253A6969%26tr%3dudp%253A%2f%2fexodus.desync.com%253A6969']
00:03:33 4227.125000 T:1562371056  NOTICE: ### [Torrenter v.2.5.2m]: Garbage collector: collected 1436 objects.
00:03:33 4227.267090 T:1956832176   ERROR: GetDirectory - Error getting plugin://plugin.video.torrenter/?action=context&url=ThePirateBay%3a%3amagnet%3a%3fxt%3durn%3abtih%3af949ea68b119a238fd7d4accb93bbea5ceb62016%26dn%3dMr.Robot.S02E08.1080p.HDTV.x264-BRISK%255BPRiME%255D%26tr%3dudp%253A%2f%2ftracker.leechers-paradise.org%253A6969%26tr%3dudp%253A%2f%2fzer0day.ch%253A1337%26tr%3dudp%253A%2f%2fopen.demonii.com%253A1337%26tr%3dudp%253A%2f%2ftracker.coppersurfer.tk%253A6969%26tr%3dudp%253A%2f%2fexodus.desync.com%253A6969
00:03:33 4227.268066 T:1956832176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.torrenter/?action=context&url=ThePirateBay%3a%3amagnet%3a%3fxt%3durn%3abtih%3af949ea68b119a238fd7d4accb93bbea5ceb62016%26dn%3dMr.Robot.S02E08.1080p.HDTV.x264-BRISK%255BPRiME%255D%26tr%3dudp%253A%2f%2ftracker.leechers-paradise.org%253A6969%26tr%3dudp%253A%2f%2fzer0day.ch%253A1337%26tr%3dudp%253A%2f%2fopen.demonii.com%253A1337%26tr%3dudp%253A%2f%2ftracker.coppersurfer.tk%253A6969%26tr%3dudp%253A%2f%2fexodus.desync.com%253A6969) failed. `

I'm using OSMC the latest one. Kodi 16.1 

Any help would be appreciated

**Comment by DiMartinoXBMC** [comment]
I think you could accidentally change onClick Action setting to Open Context Menu and it's just doesn't work now. Check in Settings, it's the one in the bootom of General

**Comment by fogenous** [comment]
Thanks @DiMartinoXBMC , this solved my issue! Also, cheers for excellent addon!Great job!
