### ISSUE TITLE
Torrenter is adding .torrent extension

### ISSUE THREAD

**Issue by mancuniancol** [DiMartinoXBMC/plugin.video.torrenter#67]
I've written an add-on which collects torrents called Magnetic and I have a connector for your amazing torrent player.

Mostly all the providers that I've written for Magnetic plays nice with Torrenter.  But, the links that Magnetic provides from Extratorrent cannot play for Torrenter.  Checking the debug log, I've found that Torrenter adds .torrent extension.  The links or torrent form Extratorrent doesn't have extension. 

Let me explain with an example:
I have an uri like this: http://website.com/download/page_direct
that link will download directly the torrent.
If I call Torrenter like:
`plugin://plugin.video.torrenter/?action=playSTRM&url=http%3A%2F%2Fwebsite.com%2Fdownload%2Fpage_direct`

Torrenter will read the url like http://website.com/download/page_direct.torrent

Not sure, if I am doing something wrong or I'm missing something.

Again, thank you for your collaboration.

**Comment by DiMartinoXBMC** [comment]
Torrenter has problems with "://" protocol (dis for browser to decide on encryption), it's a bit new and I didn't handle it, just put there "http://" or "https://"

**Comment by DiMartinoXBMC** [comment]
By the way, check out new "windowed" mode in latest version. I'm working on better navigation right now.

**Comment by mancuniancol** [comment]
OK, I will check it when I get home or tomorrow. I will give you my feedback. 

I will the modification that you suggest. Thank you.

**Comment by DiMartinoXBMC** [comment]
[This should fix it](https://github.com/DiMartinoXBMC/plugin.video.torrenter/commit/ef180cc215f36649e36697a5a5a9b0b122fddfcd)

**Comment by mancuniancol** [comment]
Yes, it does. Thank you.  I've checked the settings. I see magnetic :) Great.

**Comment by mancuniancol** [comment]
And the window search, impressive. I like a lot.
