### ISSUE TITLE
Error when Downloading

### ISSUE THREAD

**Issue by justinro** [DiMartinoXBMC/plugin.video.torrenter#7]
Hey DiMartino,
I've noticed that both the Kodi and TVAddons forums are gone, so I figured I'd reach out on the GitHub page about an error when trying to download content. It's the same one that you fixed before, so likely a site change.
Log File:
http://pastebin.com/raw.php?i=dGDBbjJN

**Comment by DiMartinoXBMC** [comment]
fixed
