### ISSUE TITLE
external devices

### ISSUE THREAD

**Issue by travka** [DiMartinoXBMC/plugin.video.torrenter#70]
Юзаю androidTV 5.1 (phillips 6401), при подключении любого девайса usb получаю ошибку чтения записи и не могу использовать его для кеша.
Есть ли какой то воркараунд ?

**Comment by DiMartinoXBMC** [comment]
Файловая структура NTFS, ext4? FAT32 не поддерживается. Аппарат рутирован?

**Comment by travka** [comment]
был fat и extfat и XFS, одинаково все.
Нет, не рутован, вот сегодня буду рутовать и пробовать замаунтить через фстаб.

**Comment by DiMartinoXBMC** [comment]
Возможно сам андройд не дает права записи. Могу только посоветовать рецепт от чувака сделать путь похожиим на \Storage\04384xxxxx\Android\data\org.xbmc.kodi\files

**Comment by travka** [comment]
да я вчера читал коммиты из libretorrent, что то такое видел.
только странно это все. Я попробую, спасибо.
