### ISSUE TITLE
Torrenter stooped working after latest update

### ISSUE THREAD

**Issue by compyy** [DiMartinoXBMC/plugin.video.torrenter#74]
Hello,

It stopped working after latest updates, here are the logs.
Nvidia Shield + Kodi 17 RC2 + Torrenter 2.6

Here are the logs

http://paste.ubuntu.com/23763695/

**Comment by DiMartinoXBMC** [comment]
thnx for report with log, should be fixed in 2.6.0a, it's in repo

**Comment by compyy** [comment]
Yes it worked, Thanks.

**Comment by DiMartinoXBMC** [comment]
good to know
