### ISSUE TITLE
Update to torrenter/torrent2http broke the plugin

### ISSUE THREAD

**Issue by compyy** [DiMartinoXBMC/plugin.video.torrenter#78]
Hi,

With latest update, unable to use it anymore it crashes as soon as you start any torrent.

logs:
http://paste.ubuntu.com/23989683/

**Comment by DiMartinoXBMC** [comment]
yep, sorry, updated torrent2http, try again

**Comment by compyy** [comment]
Hi,

No issue is not fixed :(

http://paste.ubuntu.com/24035205/

**Comment by DiMartinoXBMC** [comment]
19:09:56.857 T:138897785936   DEBUG: [torrent2http] Opening local file: /magnet:?xt=urn:btih:4fe09840c167a263
it thinks magnet is a file, will check what's wrong

**Comment by compyy** [comment]
I can clean the cache and try other torrents, will update you.

**Comment by compyy** [comment]
Hello,

It works for some, and doesnt work for few, i believe issue is same ? do you need logs again or previous logs are ok ?

**Comment by compyy** [comment]
Any plan to fix ?

**Comment by viorel-m** [comment]
@compyy try to change libtorrent version form python-libtorrent addon settings, maybe some older version will work for you

**Comment by DiMartinoXBMC** [comment]
could be solved, who knows
