### ISSUE TITLE
No module named xbmcaddon

### ISSUE THREAD

**Issue by tcjinr20** [DiMartinoXBMC/plugin.video.torrenter#82]
pip install python-xbmc

Could not find a version that satisfies the requirement python-xbmc (from versions: )
or 
pip2 install xbmcaddo

Could not find a version that satisfies the requirement xbmcaddon (from versions: )

could you tell me how can i get the xbmcaddon package

**Comment by DiMartinoXBMC** [comment]
hey, xbmcaddon is a part of Kodi (formely XBMC), addon can be used only with it, you can find it on kodi.tv
